version: '3'

services:

  postgres:
    container_name: postgres_container
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: sl+@lM!93nd3_===
      PGDATA: /data/postgres
    volumes:
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
       - ./postgres:/data/postgres
    expose:
       - "5432"
    restart: unless-stopped

  redis:
    container_name: redis_container
    image: redis
    hostname: redis
    expose:
       - "6379"
    restart: unless-stopped

  app:
    container_name: server_container
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
        - "8080:8080"
    restart: unless-stopped


